### ISSUE TITLE
Upgrade to Net Core 3.1

### ISSUE THREAD

**Issue by DejanMilicic** [websharper-samples/UrlShortener#1]
I forked the project and updated it to 3.1 
https://github.com/DejanMilicic/UrlShortener

Also, it was not compiling, so that is taken care of also.
And I simplified Paket references

@Tarmil would you be willing to accept pull request?

**Comment by Tarmil** [comment]
Definitely, go ahead :)

**Comment by DejanMilicic** [comment]
@Tarmil PR is ready!
